# Changes here will be overwritten by Copier
AddCopierCI: false
AnswerStrategy: recommended-ask
Authors: Uwe Hernandez Acosta, Simeon Ehrig
CheckExplicitImports: false
CodeOfConductContact: Uwe Hernandez Acosta
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Uwe Hernandez Acosta
MarkdownIndentation: 2
PackageName: InclusiveScans
PackageOwner: QEDjl-project
PackageUUID: ef74772d-374f-5edb-a43a-0dbb31824c9d
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
